/**
 * Plain-language bridge from what people call things to what the tariff
 * schedule calls them.
 *
 * This map, not the ranking algorithm, is what makes the tool usable. Fuzzy
 * matching cannot get from "sneakers" to "footwear with outer soles of
 * rubber" — no amount of trigram overlap bridges that. Every entry here was
 * checked against the shipped data; `npm run check:aliases` fails on any key
 * that no longer matches anything, so a list revision that drops a product
 * surfaces as a broken alias rather than a silent miss.
 *
 * Grow this from logs of searches that returned nothing. That log is the
 * roadmap for this file.
 */

export const ALIASES = {
  /* drink */
  wine: ["wine", "grape", "vermouth"],
  "red wine": ["wine", "grape"],
  "white wine": ["wine", "grape"],
  champagne: ["sparkling", "wine"],
  prosecco: ["sparkling", "wine"],
  beer: ["beer", "malt", "fermented"],
  cider: ["cider", "fermented"],
  liquor: ["spirits", "liqueurs", "alcoholic"],
  booze: ["spirits", "alcoholic", "beverages"],
  alcohol: ["alcoholic", "spirits", "alcohol"],
  spirits: ["spirits", "alcoholic"],
  whisky: ["whiskies", "spirits"],
  whiskey: ["whiskies", "spirits"],
  bourbon: ["whiskies", "bourbon", "spirits"],
  rye: ["whiskies", "spirits"],
  vodka: ["vodka", "spirits"],
  gin: ["gin", "spirits"],
  rum: ["rum", "spirits"],
  tequila: ["tequila", "spirits"],
  brandy: ["brandy", "spirits"],
  cognac: ["brandy", "spirits"],
  liqueur: ["liqueurs", "cordials"],
  "soft drink": ["beverages", "waters"],
  soda: ["beverages", "waters"],
  pop: ["beverages", "waters"],
  juice: ["juice", "beverages"],
  coffee: ["coffee"],
  tea: ["tea"],

  /* dairy and eggs */
  milk: ["milk", "cream"],
  cream: ["cream", "milk"],
  cheese: ["cheese", "cheddar", "curd"],
  cheddar: ["cheddar", "cheese"],
  mozzarella: ["mozzarella", "cheese"],
  butter: ["butter", "butterfat", "dairy"],
  yogurt: ["yogurt", "buttermilk", "milk"],
  yoghurt: ["yogurt", "buttermilk", "milk"],
  "ice cream": ["ice cream", "milk"],
  whey: ["whey"],
  "protein powder": ["whey", "protein", "casein"],
  casein: ["casein"],
  eggs: ["eggs", "birds"],
  dairy: ["milk", "cream", "cheese", "whey", "butterfat"],

  /* food */
  honey: ["honey"],
  sugar: ["sugar", "sucrose", "molasses"],
  syrup: ["syrup", "sugar", "molasses"],
  molasses: ["molasses"],
  chocolate: ["cocoa", "chocolate"],
  cocoa: ["cocoa"],
  candy: ["sugar confectionery", "confectionery"],
  sweets: ["confectionery", "sugar"],
  bread: ["bread", "bakers"],
  pastry: ["pastry", "bakers"],
  cake: ["cakes", "bakers"],
  cookies: ["biscuits", "bakers"],
  biscuits: ["biscuits", "bakers"],
  pasta: ["pasta", "macaroni"],
  cereal: ["cereal", "flakes"],
  flour: ["flour", "meal"],
  rice: ["rice"],
  beef: ["bovine", "meat"],
  pork: ["swine", "meat"],
  chicken: ["poultry", "fowls", "meat"],
  turkey: ["turkeys", "poultry"],
  meat: ["meat", "bovine", "swine", "poultry"],
  fish: ["fish", "fillets"],
  seafood: ["fish", "crustaceans", "molluscs"],
  lobster: ["crustaceans", "lobster"],
  fruit: ["fruit", "fruits"],
  vegetables: ["vegetables", "vegetable"],
  potatoes: ["potatoes"],
  tomatoes: ["tomatoes"],
  ketchup: ["tomato", "sauces"],
  sauce: ["sauces", "condiments"],
  mustard: ["mustard"],
  mayonnaise: ["sauces", "mayonnaise"],
  soup: ["soups", "broths"],
  "peanut butter": ["peanut", "ground-nut"],
  nuts: ["nuts", "almonds"],
  oil: ["oils", "oil"],
  "olive oil": ["olive", "oils"],
  vinegar: ["vinegar"],
  salt: ["salt"],
  spices: ["spices", "pepper"],
  "pet food": ["animal feeding", "dog", "cat"],
  "dog food": ["animal feeding", "dog"],

  /* cosmetics and personal care */
  makeup: ["make-up", "beauty", "cosmetic"],
  "make up": ["make-up", "beauty"],
  cosmetics: ["beauty", "make-up", "cosmetic"],
  lipstick: ["lip make-up", "lip"],
  mascara: ["eye make-up", "eye"],
  eyeliner: ["eye make-up", "eye"],
  eyeshadow: ["eye make-up", "eye"],
  foundation: ["make-up", "beauty"],
  "nail polish": ["manicure", "pedicure"],
  perfume: ["perfumes", "toilet waters"],
  cologne: ["perfumes", "toilet waters"],
  fragrance: ["perfumes", "essential oils"],
  shampoo: ["hair", "shampoos"],
  conditioner: ["hair"],
  soap: ["soap", "washing"],
  "body wash": ["soap", "washing", "organic surface-active"],
  toothpaste: ["dentifrices", "oral"],
  deodorant: ["deodorants", "antiperspirants"],
  skincare: ["skin", "beauty"],
  moisturizer: ["skin", "beauty"],
  sunscreen: ["sunscreen", "suntan", "skin"],
  shaving: ["shaving"],
  "essential oil": ["essential oils"],

  /* clothing and textiles */
  clothes: ["garments", "apparel", "clothing"],
  clothing: ["garments", "apparel", "clothing"],
  tshirt: ["t-shirts", "singlets"],
  "t shirt": ["t-shirts", "singlets"],
  "t-shirt": ["t-shirts", "singlets"],
  tee: ["t-shirts"],
  shirt: ["shirts"],
  blouse: ["blouses", "shirts"],
  sweater: ["jerseys", "pullovers", "cardigans"],
  jumper: ["jerseys", "pullovers"],
  hoodie: ["jerseys", "pullovers", "sweatshirts"],
  sweatshirt: ["sweatshirts", "pullovers"],
  jacket: ["jackets", "anoraks", "wind-jackets"],
  coat: ["overcoats", "anoraks", "coats"],
  parka: ["anoraks", "parkas"],
  raincoat: ["anoraks", "wind-jackets"],
  dress: ["dresses"],
  skirt: ["skirts"],
  pants: ["trousers", "breeches"],
  trousers: ["trousers", "breeches"],
  jeans: ["trousers", "denim"],
  shorts: ["shorts", "trousers"],
  suit: ["suits", "ensembles"],
  blazer: ["jackets", "blazers"],
  socks: ["socks", "hosiery", "stockings"],
  underwear: ["briefs", "underpants", "slips"],
  bra: ["brassieres", "bodices"],
  pyjamas: ["pyjamas", "nightdresses"],
  pajamas: ["pyjamas", "nightdresses"],
  swimsuit: ["swimwear", "bathing"],
  gloves: ["gloves", "mittens", "mitts"],
  mittens: ["gloves", "mittens", "mitts"],
  scarf: ["scarves", "shawls"],
  hat: ["headgear", "hats"],
  cap: ["headgear", "caps"],
  tie: ["ties", "cravats", "neckties"],
  belt: ["belts"],
  tracksuit: ["track suits"],
  sweatpants: ["track suits", "trousers"],
  uniform: ["garments", "apparel"],
  fabric: ["woven", "fabrics", "textile"],
  cotton: ["cotton"],
  wool: ["wool"],
  polyester: ["synthetic", "polyester"],
  silk: ["silk"],
  denim: ["denim"],
  yarn: ["yarn"],
  thread: ["thread", "yarn"],

  /* footwear */
  shoes: ["footwear", "soles"],
  sneakers: ["footwear", "sports footwear", "rubber", "soles"],
  runners: ["footwear", "sports footwear"],
  trainers: ["footwear", "sports footwear"],
  boots: ["footwear", "boots", "soles"],
  sandals: ["footwear", "sandals"],
  slippers: ["footwear", "slippers"],
  heels: ["footwear"],

  /* home textiles */
  rug: ["carpets", "floor coverings"],
  carpet: ["carpets", "floor coverings", "tufted"],
  mat: ["floor coverings", "mats"],
  flooring: ["floor coverings", "flooring", "parquet"],
  towel: ["towels", "toilet linen"],
  towels: ["towels", "toilet linen"],
  bedding: ["bed linen", "bedspreads"],
  sheets: ["bed linen"],
  blanket: ["blankets", "travelling rugs"],
  pillow: ["pillows", "cushions"],
  curtains: ["curtains", "blinds", "drapes"],
  tablecloth: ["table linen", "tablecloths"],

  /* paper */
  "toilet paper": ["toilet paper", "toilet"],
  tissues: ["facial tissues", "handkerchiefs", "cleansing"],
  kleenex: ["facial tissues", "cleansing"],
  "paper towel": ["towels", "towel stock"],
  napkins: ["serviettes", "napkins", "table"],
  diapers: ["napkins", "sanitary", "babies"],
  envelope: ["envelopes"],
  notebook: ["note books", "notebooks", "exercise"],
  diary: ["diaries", "note books"],
  paper: ["paper", "paperboard"],
  cardboard: ["corrugated", "paperboard", "cartons"],
  boxes: ["cartons", "boxes", "cases"],
  "paper cups": ["cups", "paper"],
  "paper plates": ["plates", "trays", "paper"],
  books: ["printed", "books"],
  magazine: ["periodicals", "printed"],
  newspaper: ["newspapers", "printed"],
  cards: ["cards", "printed"],
  wallpaper: ["wallpaper", "wall coverings"],
  pulp: ["pulp", "cellulose"],

  /* plastics and rubber */
  plastic: ["plastics", "polymers"],
  tupperware: ["tableware", "kitchenware", "plastics"],
  "plastic containers": ["plastics", "conveyance", "containers"],
  "plastic bags": ["sacks and bags", "plastics"],
  "garbage bags": ["sacks and bags", "plastics"],
  "cling film": ["plastics", "sheets", "film"],
  tape: ["self-adhesive", "adhesive"],
  tires: ["tyres", "tires", "rubber"],
  tyres: ["tyres", "tires", "rubber"],
  rubber: ["rubber"],
  hose: ["tubes", "pipes", "hoses"],

  /* glass, stone, ceramics */
  glass: ["glass", "glassware"],
  glassware: ["glassware", "glass", "table"],
  bottles: ["bottles", "jars", "carboys"],
  jars: ["jars", "bottles"],
  mirror: ["mirrors", "glass"],
  window: ["glass", "windows"],
  ceramic: ["ceramic", "porcelain"],
  dishes: ["tableware", "kitchenware", "ceramic"],
  plates: ["tableware", "plates"],
  mug: ["tableware", "ceramic", "cups"],
  tile: ["tiles", "ceramic"],
  cement: ["cement"],
  concrete: ["cement", "concrete"],
  drywall: ["plaster", "boards", "panels"],
  gyprock: ["plaster", "boards"],
  plaster: ["plaster"],
  insulation: ["insulating", "mineral wool", "glass wool"],

  /* wood and furniture */
  wood: ["wood", "wooden", "sawn"],
  lumber: ["sawn", "lumber", "timber"],
  timber: ["timber", "lumber", "sawn"],
  plywood: ["plywood", "veneered"],
  "particle board": ["particle board", "fibreboard"],
  mdf: ["fibreboard", "particle board"],
  veneer: ["veneer", "veneered"],
  furniture: ["furniture", "seats"],
  couch: ["upholstered", "seats", "furniture"],
  sofa: ["upholstered", "seats", "furniture"],
  chair: ["seats", "chairs", "furniture"],
  table: ["furniture", "tables"],
  desk: ["furniture", "desks", "office"],
  bed: ["furniture", "bed", "mattress"],
  mattress: ["mattress", "supports"],
  cabinets: ["cabinets", "furniture", "kitchen"],
  "kitchen cabinets": ["cabinets", "kitchen"],
  vanity: ["vanities", "cabinets"],
  shelves: ["furniture", "shelving"],
  charcoal: ["charcoal"],
  bbq: ["charcoal", "barbecue"],
  pellets: ["pellets", "wood"],

  /* metals */
  steel: ["steel", "iron", "non-alloy"],
  "stainless steel": ["stainless", "steel"],
  iron: ["iron", "steel"],
  aluminum: ["aluminum", "aluminium"],
  aluminium: ["aluminum", "aluminium"],
  copper: ["copper"],
  brass: ["copper", "brass"],
  zinc: ["zinc"],
  nickel: ["nickel"],
  rebar: ["rods", "indentations", "concrete reinforcing"],
  pipe: ["tubes", "pipes"],
  wire: ["wire"],
  nails: ["nails", "screws", "fasteners"],
  screws: ["screws", "bolts", "fasteners"],
  tools: ["tools", "hand tools"],
  hammer: ["hammers", "tools"],
  wrench: ["spanners", "wrenches", "tools"],
  drill: ["drilling", "tools"],
  knife: ["knives", "blades"],
  knives: ["knives", "blades"],
  cutlery: ["spoons", "forks", "knives", "tableware"],
  pots: ["cooking", "kitchenware", "table"],
  pans: ["cooking", "kitchenware", "frying"],
  metal: ["steel", "aluminum", "copper", "iron"],

  /* machines, electronics, vehicles */
  appliance: ["appliances", "machines", "domestic"],
  fridge: ["refrigerators", "refrigerating"],
  refrigerator: ["refrigerators", "refrigerating"],
  freezer: ["freezers", "refrigerating"],
  dishwasher: ["dish washing", "machines"],
  washer: ["washing machines", "laundry"],
  "washing machine": ["washing machines", "laundry"],
  dryer: ["drying", "laundry"],
  stove: ["cooking appliances", "stoves", "ovens"],
  oven: ["ovens", "cooking appliances"],
  microwave: ["microwave", "ovens"],
  kettle: ["electro-thermic", "appliances"],
  toaster: ["toasters", "electro-thermic"],
  vacuum: ["vacuum cleaners"],
  fan: ["fans", "ventilating"],
  "air conditioner": ["air conditioning"],
  heater: ["heaters", "electro-thermic", "space heating"],
  computer: ["automatic data processing", "computers"],
  laptop: ["automatic data processing", "portable"],
  monitor: ["monitors", "television"],
  tv: ["television", "reception apparatus"],
  television: ["television", "reception apparatus"],
  phone: ["telephones", "telephone"],
  "cell phone": ["telephones", "cellular"],
  camera: ["cameras", "television cameras"],
  printer: ["printing", "printers"],
  battery: ["batteries", "accumulators", "cells"],
  cable: ["cables", "wire", "insulated"],
  charger: ["static converters", "chargers"],
  speaker: ["loudspeakers", "sound"],
  headphones: ["headphones", "earphones"],
  lamp: ["lamps", "lighting"],
  light: ["lamps", "lighting", "luminaires"],
  bulb: ["lamps", "filament", "led"],
  motor: ["motors", "engines"],
  engine: ["engines", "motors"],
  pump: ["pumps"],
  generator: ["generators", "generating sets"],
  tractor: ["tractors", "agricultural"],
  "farm equipment": ["agricultural", "harvesting", "tractors"],
  lawnmower: ["mowers", "lawn"],
  car: ["motor cars", "vehicles", "passenger"],
  truck: ["motor vehicles", "goods", "trucks"],
  vehicle: ["vehicles", "motor"],
  auto: ["motor cars", "vehicles"],
  "car parts": ["parts", "accessories", "motor vehicles"],
  bicycle: ["bicycles", "cycles"],
  motorcycle: ["motorcycles", "cycles"],
  boat: ["vessels", "boats", "yachts"],
  trailer: ["trailers", "semi-trailers"],

  /* sport, toys, other */
  hockey: ["hockey", "ice-hockey"],
  "hockey stick": ["hockey", "sticks"],
  "fishing rod": ["fishing", "rods"],
  fishing: ["fishing", "rods", "tackle"],
  golf: ["golf"],
  ski: ["ski", "skis", "snow-ski"],
  skates: ["skates", "skating"],
  gym: ["exercise", "gymnastics", "athletics"],
  "exercise equipment": ["exercise", "gymnastics", "athletics"],
  pool: ["swimming pools", "paddling"],
  "swimming pool": ["swimming pools", "paddling"],
  toys: ["toys", "dolls", "puzzles"],
  games: ["games", "video game"],
  "board games": ["games", "puzzles"],
  bbqgrill: ["barbecue", "cooking"],
  luggage: ["trunks", "suitcases", "travel goods"],
  suitcase: ["trunks", "suitcases"],
  backpack: ["rucksacks", "backpacks", "travel goods"],
  handbag: ["handbags", "leather"],
  wallet: ["wallets", "purses", "leather"],
  leather: ["leather", "hides", "skins"],
  jewellery: ["jewellery", "jewelry", "precious"],
  jewelry: ["jewellery", "jewelry", "precious"],
  watch: ["watches", "clocks"],
  clock: ["clocks", "watches"],
  wig: ["wigs", "false beards", "hair"],
  candles: ["candles", "tapers"],
  "cleaning products": ["washing", "cleaning", "surface-active"],
  detergent: ["detergents", "washing", "surface-active"],
  bleach: ["bleaching"],
  paint: ["paints", "varnishes"],
  glue: ["adhesives", "glues"],
  fertilizer: ["fertilizers", "fertiliser"],
  pesticide: ["insecticides", "pesticides", "herbicides"],
  seeds: ["seeds", "sowing"],
  plants: ["plants", "live", "nursery"],
  flowers: ["flowers", "foliage", "bouquets"],
  medicine: ["medicaments", "pharmaceutical"],
  drugs: ["medicaments", "pharmaceutical"],
  pharma: ["pharmaceutical", "medicaments"],
  vitamins: ["vitamins", "provitamins"],
  bandage: ["wadding", "gauze", "bandages", "dressings"],
  syringe: ["syringes", "needles"],
  "medical equipment": ["medical", "surgical", "instruments"],
  glasses: ["spectacles", "lenses"],
  sunglasses: ["sunglasses", "spectacles"],
  art: ["paintings", "drawings", "art"],
  antiques: ["antiques"],
  guns: ["arms", "firearms"],
  ammunition: ["ammunition", "cartridges"],
  aircraft: ["aircraft", "aeroplanes"],
  airplane: ["aircraft", "aeroplanes"],
};

/* Words that mean "tell me about a whole sector" rather than a product. */
export const SECTOR_HINTS = {
  groceries: "Food & drink",
  food: "Food & drink",
  booze: "Food & drink",
  electronics: "Electronics",
  appliances: "Machinery & appliances",
  hardware: "Metals",
  stationery: "Pulp & paper",
};
