import React, { useState, useMemo, useRef, useEffect } from "react";

/* ------------------------------------------------------------------
   DATA LAYER
   In production these two arrays are generated by a scheduled scraper
   (see notes at bottom of file) and imported as JSON. They are inlined
   here so the prototype runs standalone.
------------------------------------------------------------------- */

// Canada's counter-tariffs on U.S.-origin goods, effective 8 Sep 2026.
// Source: Finance Canada, "Complete list of U.S. products subject to
// counter tariffs" (list updated 26 Aug 2026). Sample of ~700 lines.
const CA_MEASURES = [
  { code: "0402.10.10", rate: 50, sector: "Dairy", desc: "Milk and cream in powder, granules or solid form, fat content not over 1.5%" },
  { code: "0404.10.10", rate: 50, sector: "Dairy", desc: "Whey protein concentrate" },
  { code: "0406.10.10", rate: 25, sector: "Dairy", desc: "Fresh unripened cheese, including whey cheese, and curd" },
  { code: "0406.90.11", rate: 25, sector: "Dairy", desc: "Cheddar and cheddar-type cheese" },
  { code: "0406.90.61", rate: 25, sector: "Dairy", desc: "Mozzarella and mozzarella-type cheese" },
  { code: "0409.00.00", rate: 50, sector: "Food", desc: "Natural honey" },
  { code: "1703.10.90", rate: 50, sector: "Food", desc: "Cane molasses from the extraction or refining of sugar" },
  { code: "1901.20.11", rate: 50, sector: "Food", desc: "Mixes and doughs for bakers' wares, containing butterfat" },
  { code: "3303.00.00", rate: 50, sector: "Cosmetics", desc: "Perfumes and toilet waters" },
  { code: "3304.10.00", rate: 50, sector: "Cosmetics", desc: "Lip make-up preparations" },
  { code: "3304.20.00", rate: 50, sector: "Cosmetics", desc: "Eye make-up preparations" },
  { code: "3304.30.00", rate: 50, sector: "Cosmetics", desc: "Manicure or pedicure preparations" },
  { code: "3305.90.00", rate: 50, sector: "Cosmetics", desc: "Preparations for use on the hair, other" },
  { code: "3501.10.00", rate: 50, sector: "Dairy", desc: "Casein" },
  { code: "3918.10.90", rate: 50, sector: "Plastics", desc: "Floor coverings of vinyl chloride polymers" },
  { code: "3919.10.99", rate: 50, sector: "Plastics", desc: "Self-adhesive plastic tape in rolls not over 20 cm wide" },
  { code: "3923.21.90", rate: 50, sector: "Plastics", desc: "Sacks and bags of polyethylene" },
  { code: "3924.10.00", rate: 50, sector: "Plastics", desc: "Tableware and kitchenware of plastics" },
  { code: "3924.90.00", rate: 50, sector: "Plastics", desc: "Other household and hygienic articles of plastics" },
  { code: "4402.90.90", rate: 50, sector: "Wood", desc: "Wood charcoal, other" },
  { code: "4407.11.00", rate: 25, sector: "Wood", desc: "Pine, sawn or chipped lengthwise, over 6 mm thick" },
  { code: "4407.12.00", rate: 25, sector: "Wood", desc: "Fir and spruce, sawn or chipped lengthwise, over 6 mm thick" },
  { code: "4412.10.00", rate: 50, sector: "Wood", desc: "Plywood of bamboo" },
  { code: "4412.39.00", rate: 50, sector: "Wood", desc: "Plywood with both outer plies of coniferous wood" },
  { code: "4702.00.00", rate: 50, sector: "Pulp & paper", desc: "Chemical wood pulp, dissolving grades" },
  { code: "4803.00.00", rate: 50, sector: "Pulp & paper", desc: "Toilet or facial tissue stock, towel or napkin stock" },
  { code: "4810.13.00", rate: 50, sector: "Pulp & paper", desc: "Coated paper for writing or printing, in rolls" },
  { code: "4817.10.00", rate: 50, sector: "Pulp & paper", desc: "Envelopes of paper or paperboard" },
  { code: "4818.10.00", rate: 25, sector: "Pulp & paper", desc: "Toilet paper" },
  { code: "4818.20.00", rate: 25, sector: "Pulp & paper", desc: "Handkerchiefs, cleansing or facial tissues and towels" },
  { code: "4818.30.00", rate: 50, sector: "Pulp & paper", desc: "Tablecloths and serviettes of paper" },
  { code: "4819.10.00", rate: 50, sector: "Pulp & paper", desc: "Cartons, boxes and cases of corrugated paper or paperboard" },
  { code: "4820.10.00", rate: 50, sector: "Pulp & paper", desc: "Note books, diaries, receipt books and similar articles" },
  { code: "4823.69.00", rate: 50, sector: "Pulp & paper", desc: "Trays, dishes, plates and cups of paper or paperboard" },
  { code: "4911.91.00", rate: 50, sector: "Pulp & paper", desc: "Printed pictures, designs and photographs" },
  { code: "5701.10.90", rate: 25, sector: "Textiles", desc: "Knotted carpets of wool or fine animal hair, other" },
  { code: "5702.42.00", rate: 25, sector: "Textiles", desc: "Woven pile carpets of man-made textile materials, made up" },
  { code: "5703.29.10", rate: 25, sector: "Textiles", desc: "Machine-tufted carpets of nylon or other polyamides" },
  { code: "5703.39.10", rate: 50, sector: "Textiles", desc: "Machine-tufted carpets of other man-made textile materials" },
  { code: "5704.10.00", rate: 25, sector: "Textiles", desc: "Carpet tiles of felt, surface area not over 0.3 m²" },
  { code: "5705.00.00", rate: 25, sector: "Textiles", desc: "Other carpets and textile floor coverings" },
  { code: "6104.43.00", rate: 50, sector: "Apparel", desc: "Women's or girls' knitted dresses of synthetic fibres" },
  { code: "6104.63.00", rate: 50, sector: "Apparel", desc: "Women's or girls' knitted trousers and shorts of synthetic fibres" },
  { code: "6109.10.00", rate: 50, sector: "Apparel", desc: "T-shirts, singlets and vests of cotton, knitted" },
  { code: "6110.20.00", rate: 50, sector: "Apparel", desc: "Jerseys, pullovers and cardigans of cotton, knitted" },
  { code: "6110.30.00", rate: 50, sector: "Apparel", desc: "Jerseys, pullovers and cardigans of man-made fibres, knitted" },
  { code: "6116.93.00", rate: 50, sector: "Apparel", desc: "Gloves, mittens and mitts of synthetic fibres, knitted" },
  { code: "6201.40.90", rate: 50, sector: "Apparel", desc: "Men's or boys' anoraks and wind-jackets of man-made fibres" },
  { code: "6202.40.00", rate: 50, sector: "Apparel", desc: "Women's or girls' anoraks and wind-jackets of man-made fibres" },
  { code: "6203.11.00", rate: 50, sector: "Apparel", desc: "Men's or boys' suits of wool or fine animal hair" },
  { code: "6203.31.00", rate: 50, sector: "Apparel", desc: "Men's or boys' jackets and blazers of wool or fine animal hair" },
  { code: "6204.43.00", rate: 50, sector: "Apparel", desc: "Women's or girls' woven dresses of synthetic fibres" },
  { code: "6211.32.00", rate: 50, sector: "Apparel", desc: "Men's or boys' track suits and other garments of cotton" },
  { code: "6211.33.00", rate: 50, sector: "Apparel", desc: "Men's or boys' track suits and other garments of man-made fibres" },
  { code: "6809.11.00", rate: 50, sector: "Building materials", desc: "Plaster boards and panels faced or reinforced with paper" },
  { code: "7010.90.00", rate: 50, sector: "Glass", desc: "Glass bottles, jars, flasks and other containers, other" },
  { code: "7206.10.00", rate: 50, sector: "Steel & aluminum", desc: "Iron and non-alloy steel ingots" },
  { code: "7208.10.00", rate: 50, sector: "Steel & aluminum", desc: "Hot-rolled steel in coils, with patterns in relief" },
  { code: "7209.15.00", rate: 50, sector: "Steel & aluminum", desc: "Cold-rolled steel in coils, 3 mm or more thick" },
  { code: "7210.30.00", rate: 50, sector: "Steel & aluminum", desc: "Steel electrolytically plated or coated with zinc" },
  { code: "7210.70.00", rate: 50, sector: "Steel & aluminum", desc: "Steel painted, varnished or coated with plastics" },
  { code: "7212.30.00", rate: 50, sector: "Steel & aluminum", desc: "Narrow steel otherwise plated or coated with zinc" },
  { code: "7213.10.00", rate: 50, sector: "Steel & aluminum", desc: "Hot-rolled bars and rods in coils, with indentations (rebar)" },
];

// U.S. measures on Canadian-origin goods. Unlike Canada's single order,
// this is a STACK of separate legal authorities. Entries are grouped at
// category level: the authoritative 8- and 10-digit lines live in the
// proclamation annexes and CBP's published HTS list.
const US_MEASURES = [
  { id: "u1", rate: 50, authority: "Section 338", sector: "Alcohol", desc: "Wine, spirits and other alcoholic beverages", cusma: false, verify: true },
  { id: "u2", rate: 50, authority: "Section 338", sector: "Dairy", desc: "Milk, cream, cheese, butter and other dairy products", cusma: false, verify: true },
  { id: "u3", rate: 50, authority: "Section 338", sector: "Vehicles", desc: "Motor vehicles and listed parts", cusma: false, verify: true },
  { id: "u4", rate: 50, authority: "Section 338", sector: "Building materials", desc: "Cement", cusma: false, verify: true },
  { id: "u5", rate: 50, authority: "Section 338", sector: "Wood", desc: "Plywood and listed panel products", cusma: false, verify: true },
  { id: "u6", rate: 50, authority: "Section 338", sector: "Furniture", desc: "Furniture, listed lines", cusma: false, verify: true },
  { id: "u7", rate: 50, authority: "Section 338", sector: "Apparel", desc: "Clothing, listed lines", cusma: false, verify: true },
  { id: "u8", rate: 50, authority: "Section 338", sector: "Sporting goods", desc: "Hockey sticks and equipment, fishing rods", cusma: false, verify: true },
  { id: "u9", rate: 50, authority: "Section 338", sector: "Sporting goods", desc: "Swimming pools", cusma: false, verify: true },
  { id: "u10", rate: 50, authority: "Section 338", sector: "Agriculture", desc: "Seeds, listed lines", cusma: false, verify: true },
  { id: "u11", rate: 50, authority: "Section 338", sector: "Consumer goods", desc: "Wigs and hairpieces", cusma: false, verify: true },
  { id: "u12", rate: 50, authority: "Section 338", sector: "Glass", desc: "Decorative glassware (example line 7013.99.90)", code: "7013.99.90", cusma: false, verify: false },
  { id: "u13", rate: 50, authority: "Section 232", sector: "Steel & aluminum", desc: "Steel and aluminum, and derivative products", cusma: false, verify: true },
  { id: "u14", rate: 10, authority: "Section 232", sector: "Wood", desc: "Softwood timber and lumber", cusma: false, verify: true },
  { id: "u15", rate: 30, authority: "Section 232", sector: "Furniture", desc: "Upholstered wooden furniture (rate rose 1 Jan 2026)", cusma: false, verify: true },
  { id: "u16", rate: 50, authority: "Section 232", sector: "Furniture", desc: "Kitchen cabinets and vanities (rate rose 1 Jan 2026)", cusma: false, verify: true },
  { id: "u17", rate: 100, authority: "Section 232", sector: "Pharmaceuticals", desc: "Patented pharmaceuticals and ingredients. Generics currently exempt. In force 29 Sep 2026 for companies outside Annex III", cusma: false, verify: true },
  { id: "u18", rate: 50, authority: "Section 232", sector: "Metals", desc: "Copper and derivative products", cusma: false, verify: true },
  { id: "u19", rate: 12.5, authority: "Forced labour", sector: "Broad", desc: "Goods from economies found not to enforce forced-labour import bans. CUSMA-compliant Canadian goods are exempt", cusma: true, verify: true },
];

// Plain-language bridge. This is the piece that makes the tool usable by
// someone who has never seen an HS code. Hand-curated, grows over time.
const ALIASES = {
  wine: ["alcoholic", "wine"], beer: ["alcoholic"], liquor: ["alcoholic", "spirits"],
  booze: ["alcoholic"], whisky: ["alcoholic", "spirits"], whiskey: ["alcoholic", "spirits"],
  cheese: ["cheese"], milk: ["milk"], butter: ["dairy", "butterfat"], yogurt: ["dairy"],
  honey: ["honey"], sugar: ["molasses", "sugar"],
  makeup: ["make-up", "cosmetic"], "make up": ["make-up"], lipstick: ["lip make-up"],
  mascara: ["eye make-up"], eyeliner: ["eye make-up"], "nail polish": ["manicure"],
  perfume: ["perfume", "toilet waters"], cologne: ["perfume"], shampoo: ["hair"],
  conditioner: ["hair"], skincare: ["skin", "beauty"], sunscreen: ["sun"],
  tshirt: ["t-shirt"], "t shirt": ["t-shirt"], tee: ["t-shirt"],
  sweater: ["jerseys", "pullovers", "cardigans"], jumper: ["pullovers"], hoodie: ["pullovers", "jerseys"],
  jacket: ["anoraks", "wind-jackets", "jackets"], coat: ["overcoats", "anoraks"],
  dress: ["dresses"], pants: ["trousers"], trousers: ["trousers"], jeans: ["trousers"],
  shorts: ["shorts"], suit: ["suits"], blazer: ["blazers"], gloves: ["gloves", "mittens"],
  mittens: ["gloves", "mittens"], tracksuit: ["track suits"], sweatpants: ["track suits"],
  clothes: ["apparel", "garments"], clothing: ["apparel", "garments"],
  rug: ["carpets"], carpet: ["carpets"], mat: ["floor coverings"], flooring: ["floor coverings"],
  drywall: ["plaster boards"], gyprock: ["plaster boards"], plywood: ["plywood"],
  lumber: ["sawn", "lumber", "timber"], wood: ["wood", "sawn"], timber: ["timber", "lumber"],
  cabinets: ["cabinets"], vanity: ["vanities"], furniture: ["furniture"], couch: ["upholstered", "furniture"],
  sofa: ["upholstered", "furniture"], chair: ["furniture"],
  "toilet paper": ["toilet paper"], tissues: ["facial tissues"], kleenex: ["facial tissues"],
  "paper towel": ["towels", "tissue"], napkins: ["serviettes"], envelope: ["envelopes"],
  notebook: ["note books"], diary: ["diaries"], boxes: ["cartons", "boxes"],
  cardboard: ["corrugated"], "paper cups": ["cups"], "paper plates": ["plates"],
  tupperware: ["tableware", "kitchenware", "plastics"], "plastic containers": ["plastics", "conveyance"],
  "plastic bags": ["sacks and bags"], tape: ["self-adhesive"],
  bottles: ["bottles", "jars"], jars: ["jars"], glassware: ["glass"], glass: ["glass"],
  steel: ["steel"], aluminum: ["aluminum"], aluminium: ["aluminum"], rebar: ["rods", "indentations"],
  copper: ["copper"], metal: ["steel", "aluminum", "copper"],
  car: ["motor vehicles"], truck: ["motor vehicles"], vehicle: ["motor vehicles"],
  auto: ["motor vehicles"], "car parts": ["parts", "motor vehicles"],
  hockey: ["hockey"], "hockey stick": ["hockey"], "fishing rod": ["fishing"],
  pool: ["swimming pools"], seeds: ["seeds"], charcoal: ["charcoal"], bbq: ["charcoal"],
  medicine: ["pharmaceuticals"], drugs: ["pharmaceuticals"], pharma: ["pharmaceuticals"],
  wig: ["wigs"], cement: ["cement"], concrete: ["cement"],
};

const CA_META = { effective: "8 September 2026", updated: "26 August 2026", lines: 700, value: "$27.6B" };
const US_META = { effective: "22 August 2026", updated: "1 September 2026", lines: 554, value: "~$20B" };

/* ------------------------------------------------------------------
   SEARCH
------------------------------------------------------------------- */

const norm = (s) => s.toLowerCase().replace(/[^a-z0-9 .]/g, " ").replace(/\s+/g, " ").trim();

function trigrams(s) {
  const t = ` ${s} `;
  const out = new Set();
  for (let i = 0; i < t.length - 2; i++) out.add(t.slice(i, i + 3));
  return out;
}

function trigramScore(a, b) {
  const A = trigrams(a), B = trigrams(b);
  let hits = 0;
  A.forEach((g) => { if (B.has(g)) hits++; });
  return hits / Math.max(A.size, 1);
}

function expandQuery(q) {
  const n = norm(q);
  const terms = new Set(n.split(" ").filter(Boolean));
  Object.keys(ALIASES).forEach((k) => {
    if (n.includes(k)) ALIASES[k].forEach((v) => terms.add(v));
  });
  return [...terms];
}

function scoreItem(item, rawQuery, terms) {
  const hay = norm(`${item.desc} ${item.sector} ${item.code || ""} ${item.authority || ""}`);
  const q = norm(rawQuery);
  if (!q) return 0;

  // Code prefix match wins outright.
  const bare = q.replace(/\./g, "");
  if (item.code && item.code.replace(/\./g, "").startsWith(bare) && bare.length >= 2) return 100;

  let score = 0;
  if (hay.includes(q)) score += 40;
  terms.forEach((t) => {
    if (t.length < 3) return;
    if (hay.includes(t)) score += 12;
  });
  if (score === 0) {
    const fz = trigramScore(q, hay);
    if (fz > 0.14) score += fz * 30;
  }
  return score;
}

function search(items, query) {
  if (!query.trim()) return items.map((i) => ({ item: i, score: 0 }));
  const terms = expandQuery(query);
  return items
    .map((i) => ({ item: i, score: scoreItem(i, query, terms) }))
    .filter((r) => r.score > 4)
    .sort((a, b) => b.score - a.score);
}

/* ------------------------------------------------------------------
   UI
------------------------------------------------------------------- */

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,600;0,800;1,400&display=swap');
.tc *{box-sizing:border-box;margin:0;padding:0}
.tc{
  --paper:#FBFAF8; --ink:#1A2129; --dim:#5C6672; --rule:#DEDAD2;
  --us:#1F5C8B; --ca:#A32A2A;
  --r15:#B08300; --r25:#C4661F; --r50:#A8291A;
  font-family:'Public Sans',system-ui,sans-serif;
  background:var(--paper); color:var(--ink);
  min-height:100vh; padding:0 0 5rem;
  font-size:16px; line-height:1.5; -webkit-font-smoothing:antialiased;
}
.tc .wrap{max-width:660px;margin:0 auto;padding:0 1.15rem}
.tc h1{font-size:1.65rem;font-weight:800;letter-spacing:-.022em;line-height:1.15}
.tc h2{font-size:1.05rem;font-weight:700;letter-spacing:-.01em}
.tc .sub{color:var(--dim);font-size:.9rem;line-height:1.55}
.tc .masthead{border-bottom:2px solid var(--ink);padding:1.4rem 0 .9rem;margin-bottom:1.25rem}
.tc .flagline{display:flex;gap:.4rem;align-items:center;margin-bottom:.55rem}
.tc .chip{width:10px;height:10px;border-radius:2px}
.tc .chip.us{background:var(--us)} .tc .chip.ca{background:var(--ca)}
.tc .flagline span{font-size:.76rem;font-weight:600;color:var(--dim);letter-spacing:.04em}

.tc .tabs{display:flex;gap:.3rem;border-bottom:1px solid var(--rule);margin-bottom:1.2rem}
.tc .tab{background:none;border:none;font:inherit;font-weight:600;font-size:.9rem;
  padding:.6rem .7rem;color:var(--dim);cursor:pointer;border-bottom:3px solid transparent;
  margin-bottom:-1px;transition:color .12s}
.tc .tab[data-on="1"]{color:var(--ink);border-bottom-color:var(--ink)}
.tc .tab:focus-visible{outline:2px solid var(--us);outline-offset:2px;border-radius:3px}

.tc .dirbtn{display:block;width:100%;text-align:left;background:#fff;border:1px solid var(--rule);
  border-left:5px solid var(--edge,var(--rule));padding:.95rem 1rem;margin-bottom:.6rem;
  font:inherit;cursor:pointer;border-radius:3px;transition:border-color .12s,transform .08s}
.tc .dirbtn:hover{border-color:var(--edge)} .tc .dirbtn:active{transform:translateY(1px)}
.tc .dirbtn:focus-visible{outline:2px solid var(--ink);outline-offset:2px}
.tc .dirbtn b{display:block;font-weight:700;font-size:1rem;margin-bottom:.15rem}
.tc .dirbtn em{font-style:normal;color:var(--dim);font-size:.85rem;line-height:1.45;display:block}

.tc .field{width:100%;font:inherit;font-size:1rem;padding:.8rem .9rem;border:1.5px solid var(--ink);
  border-radius:3px;background:#fff;color:var(--ink)}
.tc .field:focus{outline:3px solid rgba(31,92,139,.28);outline-offset:1px}
.tc .field::placeholder{color:#969DA6}

.tc .filters{display:flex;flex-wrap:wrap;gap:.35rem;margin:.75rem 0 .3rem}
.tc .pill{font:inherit;font-size:.78rem;font-weight:600;padding:.3rem .6rem;border-radius:999px;
  border:1px solid var(--rule);background:#fff;color:var(--dim);cursor:pointer}
.tc .pill[data-on="1"]{background:var(--ink);border-color:var(--ink);color:#fff}
.tc .pill:focus-visible{outline:2px solid var(--us);outline-offset:2px}

.tc .row{border-bottom:1px solid var(--rule);padding:.85rem 0;display:flex;gap:.85rem;align-items:flex-start}
.tc .rate{flex:0 0 3.4rem;text-align:right;font-variant-numeric:tabular-nums;
  font-weight:800;font-size:1.15rem;letter-spacing:-.03em;line-height:1.2;padding-top:.05rem}
.tc .rate small{display:block;font-size:.62rem;font-weight:600;color:var(--dim);letter-spacing:.03em}
.tc .body{flex:1;min-width:0}
.tc .body p{font-size:.93rem;line-height:1.45}
.tc .metaline{font-size:.76rem;color:var(--dim);margin-top:.28rem;font-variant-numeric:tabular-nums}
.tc .code{font-weight:700;color:var(--ink)}
.tc .warn{display:inline-block;margin-top:.35rem;font-size:.73rem;color:var(--r25);
  border:1px solid currentColor;border-radius:2px;padding:.05rem .35rem;font-weight:600}

.tc .stats{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:var(--rule);
  border:1px solid var(--rule);border-radius:3px;overflow:hidden;margin:1.1rem 0}
.tc .stat{background:#fff;padding:.85rem .9rem}
.tc .stat b{display:block;font-size:1.5rem;font-weight:800;letter-spacing:-.03em;
  font-variant-numeric:tabular-nums;line-height:1.1}
.tc .stat span{font-size:.76rem;color:var(--dim);line-height:1.35;display:block;margin-top:.2rem}

.tc .note{background:#fff;border:1px solid var(--rule);border-left:5px solid var(--edge,var(--dim));
  padding:.85rem .95rem;border-radius:3px;margin:1rem 0;font-size:.88rem;line-height:1.5}
.tc .note b{font-weight:700}
.tc .empty{padding:2rem 0;color:var(--dim);font-size:.92rem;line-height:1.55}
.tc .foot{margin-top:2.5rem;padding-top:1.1rem;border-top:1px solid var(--rule);
  font-size:.78rem;color:var(--dim);line-height:1.6}
.tc a{color:var(--us)}
.tc .back{background:none;border:none;font:inherit;font-size:.85rem;font-weight:600;
  color:var(--dim);cursor:pointer;padding:.3rem 0;margin-bottom:.5rem}
.tc .back:focus-visible{outline:2px solid var(--us);outline-offset:2px}
@media (max-width:420px){ .tc .stats{grid-template-columns:1fr} }
@media (prefers-reduced-motion:reduce){ .tc *{transition:none!important} }
`;

const rateColor = (r) => (r >= 50 ? "var(--r50)" : r >= 25 ? "var(--r25)" : "var(--r15)");

function Row({ item, side }) {
  return (
    <div className="row">
      <div className="rate" style={{ color: rateColor(item.rate) }}>
        {item.rate}%
        <small>added</small>
      </div>
      <div className="body">
        <p>{item.desc}</p>
        <div className="metaline">
          {item.code && <span className="code">{item.code}</span>}
          {item.code && " · "}
          {item.sector}
          {item.authority && ` · ${item.authority}`}
        </div>
        {side === "us" && item.verify && (
          <span className="warn">Category level — check your exact HTS line</span>
        )}
      </div>
    </div>
  );
}

function ListView({ side }) {
  const [q, setQ] = useState("");
  const [rateF, setRateF] = useState(null);
  const data = side === "ca" ? CA_MEASURES : US_MEASURES;
  const meta = side === "ca" ? CA_META : US_META;

  const results = useMemo(() => {
    let r = search(data, q).map((x) => x.item);
    if (rateF) r = r.filter((i) => i.rate === rateF);
    return r;
  }, [q, rateF, data]);

  const rates = useMemo(
    () => [...new Set(data.map((d) => d.rate))].sort((a, b) => a - b),
    [data]
  );

  return (
    <div>
      <p className="sub" style={{ marginBottom: ".8rem" }}>
        {side === "ca" ? (
          <>Canada's counter-tariffs on goods of U.S. origin. In force {CA_META.effective}, covering
          about {CA_META.lines} tariff items and {CA_META.value} in imports.</>
        ) : (
          <>U.S. measures on goods of Canadian origin. These come from several separate
          authorities that stack on top of each other and on the base duty rate.</>
        )}
      </p>

      <input
        className="field"
        value={q}
        onChange={(e) => setQ(e.target.value)}
        placeholder={side === "ca" ? "Try “wine”, “toilet paper”, or 6109" : "Try “hockey sticks” or “cabinets”"}
        aria-label="Search products"
      />

      <div className="filters">
        <button className="pill" data-on={rateF === null ? "1" : "0"} onClick={() => setRateF(null)}>
          All rates
        </button>
        {rates.map((r) => (
          <button key={r} className="pill" data-on={rateF === r ? "1" : "0"} onClick={() => setRateF(r)}>
            {r}%
          </button>
        ))}
      </div>

      <p className="metaline" style={{ marginBottom: ".4rem" }}>
        {results.length} {results.length === 1 ? "match" : "matches"} · list updated {meta.updated}
      </p>

      {results.length === 0 ? (
        <div className="empty">
          Nothing matched that. Try a broader word — “cheese” rather than a brand,
          “jacket” rather than “parka” — or enter the first four digits of an HS code.
        </div>
      ) : (
        results.map((item, i) => <Row key={item.code || item.id || i} item={item} side={side} />)
      )}
    </div>
  );
}

function Triage({ onPick }) {
  const [step, setStep] = useState(0);
  const [dir, setDir] = useState(null);
  const [kind, setKind] = useState(null);

  if (step === 0) {
    return (
      <div>
        <h2 style={{ marginBottom: ".2rem" }}>Which way is it moving?</h2>
        <p className="sub" style={{ marginBottom: ".9rem" }}>
          What matters is where the goods were made, not where the parcel was posted from.
        </p>
        <button className="dirbtn" style={{ "--edge": "var(--ca)" }}
          onClick={() => { setDir("ca"); setStep(1); }}>
          <b>Coming into Canada from the U.S.</b>
          <em>Canada's counter-tariffs may apply</em>
        </button>
        <button className="dirbtn" style={{ "--edge": "var(--us)" }}
          onClick={() => { setDir("us"); setStep(1); }}>
          <b>Going into the U.S. from Canada</b>
          <em>U.S. Section 338, Section 232 and other duties may apply</em>
        </button>
      </div>
    );
  }

  if (step === 1) {
    return (
      <div>
        <button className="back" onClick={() => setStep(0)}>← Change direction</button>
        <h2 style={{ marginBottom: ".2rem" }}>Who's bringing it in?</h2>
        <p className="sub" style={{ marginBottom: ".9rem" }}>
          Personal and commercial shipments follow different rules.
        </p>
        <button className="dirbtn" onClick={() => { setKind("personal"); setStep(2); }}>
          <b>It's for me</b>
          <em>A parcel, an online order, something I'm bringing back</em>
        </button>
        <button className="dirbtn" onClick={() => { setKind("commercial"); setStep(2); }}>
          <b>It's for a business</b>
          <em>Stock, materials, or anything entered commercially</em>
        </button>
      </div>
    );
  }

  const edge = dir === "ca" ? "var(--ca)" : "var(--us)";
  return (
    <div>
      <button className="back" onClick={() => setStep(1)}>← Change who's importing</button>

      {kind === "personal" && (
        <div className="note" style={{ "--edge": edge }}>
          <b>Personal shipments aren't always caught.</b> Low-value and casual goods can fall under
          separate rules, and the courier or customs broker makes the final call. Treat what follows
          as “is this product category on the list”, not as a bill.
        </div>
      )}

      {dir === "ca" && (
        <div className="note" style={{ "--edge": edge }}>
          <b>Origin, not shipping address.</b> Canada's counter-tariffs apply to goods that qualify to
          be marked as a good of the U.S. under the CUSMA marking rules. Something made in Vietnam
          and shipped from a warehouse in Ohio is not a U.S.-origin good.
        </div>
      )}

      {dir === "us" && (
        <div className="note" style={{ "--edge": edge }}>
          <b>A CUSMA certificate won't help here.</b> Section 338 applies to covered goods regardless
          of CUSMA origin status, which reverses the usual assumption. What decides it is whether the
          specific HTS line appears in one of the three annexes.
        </div>
      )}

      <button className="dirbtn" style={{ "--edge": edge }} onClick={() => onPick(dir)}>
        <b>Search the {dir === "ca" ? "Canadian" : "U.S."} list</b>
        <em>By product name or HS code</em>
      </button>
    </div>
  );
}

function Home({ go }) {
  return (
    <div>
      <Triage onPick={go} />

      <h2 style={{ marginTop: "2rem" }}>Where things stand</h2>
      <div className="stats">
        <div className="stat">
          <b style={{ color: "var(--us)" }}>{US_META.value}</b>
          <span>Canadian goods hit by the U.S. 50% Section 338 duty, in force since {US_META.effective}</span>
        </div>
        <div className="stat">
          <b style={{ color: "var(--ca)" }}>{CA_META.value}</b>
          <span>U.S. goods matched dollar for dollar by Canada from {CA_META.effective}</span>
        </div>
        <div className="stat">
          <b>{CA_META.lines}+</b>
          <span>tariff items on Canada's list, at 15%, 25% or 50%</span>
        </div>
        <div className="stat">
          <b>{US_META.lines}</b>
          <span>HTS codes named in the U.S. Section 338 annexes</span>
        </div>
      </div>

      <div className="note">
        <b>These duties stack.</b> A tariff here is added on top of the ordinary duty a product
        already owes, plus any other applicable fees — it doesn't replace it.
      </div>
    </div>
  );
}

export default function TariffChecker() {
  const [tab, setTab] = useState("home");
  const top = useRef(null);
  useEffect(() => { top.current?.scrollIntoView({ block: "start" }); }, [tab]);

  return (
    <div className="tc">
      <style>{CSS}</style>
      <div className="wrap" ref={top}>
        <header className="masthead">
          <div className="flagline">
            <i className="chip us" /><i className="chip ca" />
            <span>Canada–U.S. tariffs · updated 5 September 2026</span>
          </div>
          <h1>Is my product tariffed?</h1>
          <p className="sub" style={{ marginTop: ".4rem" }}>
            A plain-language look at what each country is charging the other, and whether
            the thing you're buying or shipping is on a list.
          </p>
        </header>

        <nav className="tabs">
          {[["home", "Start here"], ["us", "U.S. tariffs"], ["ca", "Canada's tariffs"]].map(([k, label]) => (
            <button key={k} className="tab" data-on={tab === k ? "1" : "0"} onClick={() => setTab(k)}>
              {label}
            </button>
          ))}
        </nav>

        {tab === "home" && <Home go={setTab} />}
        {tab === "us" && <ListView side="us" />}
        {tab === "ca" && <ListView side="ca" />}

        <footer className="foot">
          <p>
            <b>This is not customs advice.</b> Product descriptions here are simplified and the
            underlying lists change often. Classification and entry decisions should go through a
            licensed customs broker. Verify against Finance Canada's published list and CBP's
            Section 338 HTS list before relying on anything you see here.
          </p>
          <p style={{ marginTop: ".7rem" }}>
            Prototype dataset. Canadian entries are a sample of the ~700 published tariff items;
            U.S. entries are grouped at category level pending ingestion of the full annexes.
          </p>
        </footer>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------------
   PRODUCTION NOTES

   1. Ingestion. Two scrapers, run on a schedule, writing versioned JSON:
      - canada.js  → parses the Finance Canada HTML table. Stable columns:
                     tariff item, HS heading, indicative description, rate.
      - us.js      → harder. Section 338 annexes render as images in the
                     Federal Register, so pull the White House annex PDFs and
                     CBP's CSMS #69606660 HTS list attachment instead. Section
                     232 actions are separate proclamations; keep them as
                     distinct records with their own effective dates.
      Commit the diff. The commit history becomes a free "what changed"
      feed, which no existing portal offers.

   2. Search. Currently alias map + substring + trigram fallback, no deps.
      At full data size (~1,300 rows) that is still fine client-side, but
      MiniSearch would give better ranking and prefix handling for little cost.
      The alias map is the real asset — grow it from search logs of queries
      that returned nothing.

   3. Trade values. To rank by importance, join StatCan CIMT and US Census
      DataWeb figures at HS-6 only. National 8- and 10-digit codes diverge
      between the two countries; joining below 6 digits produces silent errors.

   4. Staleness. Show the "as of" date on every screen and fail loud: if the
      scraper hasn't succeeded in N days, banner it rather than serving old
      data quietly.
------------------------------------------------------------------- */
